### PR TITLE
Redesign

### PR DESCRIPTION
**Pull request by itsjustdel**
#### A lovely redesign to please the eyes:

image
image
image
image

### CODE REVIEW

**Review by andydotxyz — APPROVED** [review]
I love it :)

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Oh, hold on - a bunch of app images got committed - they should be used directly from the app metadata rather than served from this repo

**Review by andydotxyz — APPROVED** [review]
Looking great!

**Comment by itsjustdel** [comment]
Woo, thanks!

**Comment by andydotxyz** [comment]
We could add something like that, would it be per-app or just for the home page?
One consideration is that it would mean app develops adding more metadata to be able to list their apps, and I don't think we should add more requirements if we can avoid it.
If you want to pursue this further please open an issue.

**Comment by Jacalz** [comment]
Sounds like a good idea but I I think that discussion is better discussed in it's own ticket.

**Pull request merged**
